name: barcode_scanner
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.6
  qr_flutter: ^4.0.0
  image_compare: ^1.1.2
  image_picker: ^0.8.7
  image_gallery_saver: ^1.7.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-qr-code1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/